// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tndmjofklolancbhchbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZG1qb2ZrbG9sYW5jYmhjaGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjE1NjAsImV4cCI6MjA3MTI5NzU2MH0.OUynHXWf8Ak8z9S0lWd_FtlPcOjJ4p-B_1yE-BfuzaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});